language: python
python:
  - "2.7"
  - "3.7"
cache: pip
before_install:
  - sudo apt-get -y install gcc gfortran
install:
  - pip install -r requirements.txt
script:
  - python app/monitor.py -D -T
  - python telegram/telegrambot.py -T
  - python app/threshold.py -D -T
  - python app/file_upload.py -j conf/fileuploadjobs.json
  - python core/acquisitionsupport.py
  - python core/martas.py
